name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build binary
        run: zip -r deployment.zip .
          
      
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: thebridge
          zip_file: deployment.zip
          #memory_size: 512
          #timeout: 30
          #handler: app.handler
          #role: ${{ secrets.AWS_LAMBDA_MS_IAM_ROLE }}
          #runtime: python3.7
          #environment: env=dev