name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # checkout the correct branch name
          fetch-depth: 0 # fetch the whole repo history

      - name: Build binary
        run: zip -r deployment.zip .
          
      
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: thebridge
          zip_file: deployment.zip
          #memory_size: 512
          #timeout: 30
          #handler: app.handler
          #role: ${{ secrets.AWS_LAMBDA_MS_IAM_ROLE }}
          #runtime: python3.7
          #environment: env=dev